### ISSUE TITLE
Waypoints use up no Artron Energy from the batteries whatsoever

### ISSUE THREAD

**Issue by ShellSnake** [SpectrumFATM/MoreVortexManipulators#2]
For some reason it's free to use as long as you get to where you wanna be first, however, they can also be used inside anyone's Tardis making it hard to invite people over without having privacy breaches.

**Comment by SpectrumFATM** [comment]
That is a known bug to be fixed in the next update as I do not feel a resolution has to be urgent.

On the topic of being able to save waypoints in TARDISes, that is an intentional feature. I'd suggest you do not invite anyone untrustworthy into your TARDIS in the first place to prevent security breaches.
